### ISSUE TITLE
버그: 프로젝트 생성 시 에러가 발생해 프로젝트를 생성할 수 없음에도 스피너 동작하고 있음

### ISSUE THREAD

**Issue by HalamLee** [jujoycode/fury-tool#4]
Fury 프로젝트 내부에서 프로젝트 생성을 시도했을 때 에러가 발생했습니다.
에러 로그에는 프로젝트를 생성할 수 없다고 하나, 프로그램이 종료되지 않고 Creating project... 문구의 로딩 스피너가 계속 돌아가는 현상이 있습니다.

<img width="613" alt="image" src="https://github.com/user-attachments/assets/e9f64db1-21b9-4c63-869a-6abfde768615">

**Comment by jujoycode** [comment]
@HalamLee

> Ora 관련 예외 처리가 없었던 결함 수정 (연관 6건 수정)
    ![image](https://github.com/user-attachments/assets/b067e4bc-87a6-49c2-bd16-f2d19ebf1f82)
    ![image](https://github.com/user-attachments/assets/a1face8e-7c0a-469a-b45a-d4c46fd78e38)
